version: '3.8'

services:
  fastapi: 
    build: .
    container_name: fastapi_app
    env_file: app/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
